name = "TinyRegistry"
uuid = "b339939d-be5c-48e7-850e-6d7a29bc8aad"
repo = "https://github.com/brianyjtai1994/TinyRegistry.git"
description = "A small `Julia` registry repo for my daily works."

[packages]
f61ef0c9-d2b1-4370-9f73-58bf29aadc66 = { name = "ApproxInference", path = "ApproxInference" }
0556ab4a-33c4-4427-92d2-b6051d932f38 = { name = "GlobalOptimizer", path = "GlobalOptimizer" }
b954bf54-d75b-427c-a758-91b02d854ca4 = { name = "SolveDiffEq", path = "SolveDiffEq" }
fc16d259-17d0-45d5-b352-c4a79ee8968e = { name = "Spectroscopy", path = "Spectroscopy" }
4c485984-08a4-4805-a31a-4ac085ba158c = { name = "TinyFFT", path = "TinyFFT" }
